<div class="liquido-container">
    <h1>Liquido Pagamentos</h1>
    <h2>Escolha como quer pagar</h2>
    <?php
    $brazil_payin_methods = $this->getLiquidoBrazilPayInMethods();
    ?>

    <ul>
        <?php foreach ($brazil_payin_methods as $payin_method) : ?>
            <li>
                <a href="<?php echo $this->getPayInMethodViewRoute($payin_method) ?>"><?php echo $payin_method; ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>