<style>
    .error-message {
        padding: 12px;
        border-radius: 3px;
        background-color: #ffcccc;
        color: #ff4d4d;
        font-weight: bold;
    }
</style>
<div class="liquido-container">
    <h1>Liquido Pagamentos</h1>
    <?php if ($this->getErrorMsg() != null) : ?>
        <div class="error-message">
            <div>
                <?php echo $this->getErrorMsg() ?>
            </div>
        </div>
    <?php else : ?>
        <h2>Escaneie o código QR pelo seu app de pagamentos ou Internet Banking</h2>
        <h3>Número do pedido: <?php echo $this->getOrderId() ?></h3>
        <img style="height: 400px;" src="https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl=<?php echo $this->getPixCode() ?>&choe=UTF-8" alt="QR Code">
        <hr />
        <div id="pix-code-copy-paste">
            <fieldset class="fieldset">
                <label for="pix-code">Se preferir, você pode pagá-lo copiando e colando o código abaixo:</label><br>
                <input type="text" id="pix-code" name="pix-code" readonly value="<?php echo $this->getPixCode() ?>"><br>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button onclick="copyToClipboard()" class="action primary" title="<?php echo __('Copiar código') ?>">
                        <span><?php echo __('Copiar código') ?></span>
                    </button>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
<script>
    function copyToClipboard() {
        /* Get the text field */
        var copyText = document.getElementById("pix-code");

        /* Select the text field */
        copyText.select();
        copyText.setSelectionRange(0, 99999); /* For mobile devices */

        /* Copy the text inside the text field */
        navigator.clipboard.writeText(copyText.value);

        /* Alert the copied text */
        alert("Pix Copiado!");
    }
</script>